decision_logs:
    service: oma
    reporting:
        min_delay_seconds: 1
        max_delay_seconds: 3
    console: true

services:
    nid-policies-registry:
        url: https://gitlab.com/api/v4/projects/55642500/packages/generic/bundle # First part of the bundle URL
    oma:
        url: http://localhost:8080/api/decision-log
        response_header_timeout_seconds: 5

# status:
#     service: oma

bundles:
    nid-policies-registry:
        service: nid-policies-registry
        resource: latest/bundle.tar.gz # Second part of the bundle URL
        persist: true
        polling:
        min_delay_seconds: 5
        max_delay_seconds: 30
        signing:
        keyid: authz

keys:
    default:
        key: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw3mEVnnPe2amkJ7b7OO7
            ZUywOqUEoeCohiEx17cE0nIJ1brHYh4lcuSBZGqLOK5JWhwZvr3cUzaXr+D5j7eF
            wM2epULzkFCJcDiVTobHS40vMoFtdUxib1DVZlHXkotvVCrNcjqNgNfeQ9WNXPT5
            gKgedhteqp8Wr0AcXD0TQgeaGg1XSZaNIk09QCQP1YRmATEcRqEZcXnTwwuz+2+A
            wExGe8224YEDIhkUDSEFym3QQcYahivONzzVmU1mm8MFCfpwJlkiFkQ6D9mPLsoI
            3ccBd02wMJk+mFU4mVpDMoQ2D+s/CUKr3+FaZklf6mpjUYswwkJ3UnR4BwVLPTG3
            5wIDAQAB
            -----END PUBLIC KEY-----
