name: Release

on:
  push:
    tags:
      - '**'

jobs:
  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ui/dist

  build-api:
    needs: build-ui
    runs-on: ubuntu-latest
    strategy:
        matrix:
          arch: [arm, arm64, amd64, 386]
          os: [linux, darwin, freebsd, windows]
          exclude:
            - os: darwin
              arch: arm
            - os: darwin
              arch: 386
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.1

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ui/dist

      - name: Build Golang API
        run: env GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} CGO_ENABLED=0 go build -o oma-${{matrix.os}}-${{matrix.arch}}

      - name: Upload API artifact
        uses: actions/upload-artifact@v2
        with:
          name: oma-${{matrix.os}}-${{matrix.arch}}
          path: oma-${{matrix.os}}-${{matrix.arch}}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: oma-${{matrix.os}}-${{matrix.arch}}
          name: 
